name: Gemini CLI

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  gemini-cli:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit
          disable-telemetry: true

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch tags
        id: fetch_tags
        run: |
          git fetch --tags

      - name: Generate release notes
        uses: google-gemini/gemini-cli-action@main
        with:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          version: latest
          settings_json: |
            {
              "sandbox": true,
              "autoAccept": true
            }
          prompt: |
            My release changes are listed in the file named CHANGELOG.txt.
            make a list of all notable changes and categorize it nicely with emojis, output
            as Markdown and a one liner of the change. Add a jira link for each change if specified in the commit message. put the link in the begining of the line.
            include all changes that have a  jira link.
            preface the release notes with a brief summary of the release.
            also save the release notes in a file named "release-notes.md".

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-notes
          path: release-notes.md


  create-release:
    needs: gemini-cli
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit
          disable-telemetry: true

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: release-notes

      - name: Create a release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
        with:
          name: "v1.1.303"
          tag_name: "v1.1.303"
          body_path: "release-notes.md"
          make_latest: false
          generate_release_notes: false
