# Copyright The Conforma Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

---
name: Release

on:
  workflow_dispatch:
  # schedule:
    # - cron: '0 9 * * 3'

# Allow only one instance of this workflow to run at a time.
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  get_info:

    runs-on: ubuntu-latest
    outputs:
      latest_tag: ${{ steps.get_latest_tag.outputs.latest_tag }}
      latest_tag_sha: ${{ steps.get_latest_tag.outputs.latest_tag_sha }}
      changed: ${{ steps.has_changed.outputs.changed }}
      next_version: ${{ steps.bump.outputs.next_version }}
  
    env:
        TRACKED_PATHS: "acceptance/ policy/"

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Obtain latest tag
        id: get_latest_tag
        run: |
          set -ex
          git fetch --tags
          tag=$(git describe --tags --abbrev=0 --match="v[0-9]*" main)
          echo latest_tag=$tag | tee -a "$GITHUB_OUTPUT"
          echo latest_tag_sha=$(git rev-parse "$tag") | tee -a "$GITHUB_OUTPUT"

      - name: Check if tracked files/dirs have changed
        id: has_changed
        run: |
          set -ex
          latest_tag_sha=${{ steps.get_latest_tag.outputs.latest_tag_sha }}
          changed=false
          diff=$(git diff --name-only $latest_tag_sha $TRACKED_PATHS)
          [ -z "$diff" ] || changed=true
          echo "changed=$changed" | tee -a "$GITHUB_OUTPUT"

      - name: Get next version
        id: bump
        run: |
          set -ex
          latest_tag=${{ steps.get_latest_tag.outputs.latest_tag }}
          next_version=$(echo "$latest_tag" | awk -F. -v OFS=. '{$NF++;print}')
          echo "next_version=$next_version" | tee -a "$GITHUB_OUTPUT"
        
  
  create_release:

    needs: get_info
    if: needs.get_info.outputs.changed
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add tag
        run: |
          set -ex
          NEW_TAG="${{ needs.get_info.outputs.next_version }}"

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"          

          git tag -a -f -m "New version added automatically" "$NEW_TAG"
          git push --tags
        
      - name: Create a release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2
        with:
          make_latest: false
          name: ${{ needs.get_info.outputs.next_version }}
          tag_name: ${{ needs.get_info.outputs.next_version }}
          generate_release_notes: false
          files: ${{TRACKED_PATHS}}
